# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerrex_tasker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kerrex_tasker.PriorityDict'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_permission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kerrex_tasker.PermissionDict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprojectpermission',
            name='permission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kerrex_tasker.PermissionDict'),
            preserve_default=False,
        ),
    ]
