# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerrex_tasker', '0002_auto_20170708_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissionDict',
            new_name='Permission',
        ),
        migrations.RenameModel(
            old_name='PriorityDict',
            new_name='Priority',
        ),
    ]
