# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerrex_tasker', '0003_auto_20170708_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order_in_category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('project', 'order_in_project')]),
        ),
    ]
