# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerrex_tasker', '0004_auto_20170807_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set([('order_in_category', 'category')]),
        ),
    ]
