# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerrex_tasker', '0006_auto_20170813_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='show_on_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
