# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerrex_tasker', '0008_usercardnotification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardnotification',
            name='minutes_before_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
